### ISSUE TITLE
Mouse curser problem

### ISSUE THREAD

**Issue by johanruda** [InvisibleShield/FFXIV-Zodiac-Glass#2] opened 2015-01-22 17:20 UTC
First of all, thank you for this awesome overlay!

My issue is this; 
Normally when I use my right mouse button to turn my character around, the curser disappears but actually stays where I first pressed the button and then pops up at the same spot when I release the button again.
However, with this overlay, the curser still disappears but moves as I drag the mouse. This is especially troublesome when you use two monitors like I do as the curser often pops up on the other monitor and I start clicking outside the game.

I'm playing the game in 1080p borderless windowed mode. If you need any more info, let me know!

Thanks again and I hope you can fix this as I love this little program. It's incredibly useful :)

**Comment by InvisibleShield** [comment] 2015-01-23 18:14
Hey johanruda,

I can't reproduce the behavior that you described.

Is it always happens?
Which version do you use?
Is this problem still there if you disable your second monitor?

**Comment by InvisibleShield** [comment] 2015-02-24 21:56
It happens randomly. It will be hard to find a solution because it seems like an error on SE side.

**Comment by InvisibleShield** [comment] 2015-02-27 09:17
I created a new overlaying mechanism. 
This will fix the issue.
Please look forward to the next release.

**Comment by InvisibleShield** [comment] 2015-02-28 19:32
Fixed with [Release v1.3.1502.28000](https://github.com/InvisibleShield/FFXIV-Zodiac-Glass/releases/tag/v1.3.1502.28000).

**Closed by InvisibleShield** 2015-02-28 19:32 UTC
